"""The catalog — one source of truth for every page.

This drives BOTH rendering and ingestion. A page is a list of panels; a panel
row carries the identifier that fetches it (`series` for FRED, `symbol` for
Yahoo, `derived` for locally computed, `manual` for anything hand-entered), so
the ETL can walk this file to learn what to fetch and the templates walk the
same file to lay it out. Previously those two facts lived in different places —
data-* attributes in 29 hand-written HTML files — and could drift apart.

Panel types: links, metrics, quotes, stories, chains, note.

Keys are URL paths: "" is the home page, "sections/macro/inflation" is
/sections/macro/inflation. Prose is trusted HTML and rendered unescaped.
"""

PAGES = {'': {'title': 'cobalt',
      'h1': 'Cobalt',
      'section': 'home',
      'tagline': 'personal intelligence platform',
      'show_refreshed': True,
      'refresh': True,
      'refresh_label': 'Refresh all data',
      'summarize': False,
      'panels': [{'type': 'links',
                  'heading': 'news',
                  'items': [{'href': '/sections/news', 'label': 'all news'},
                            {'href': '/sections/news/politics', 'label': 'politics'},
                            {'href': '/sections/news/economics', 'label': 'economics'},
                            {'href': '/sections/news/tech', 'label': 'technology &amp; science'}]},
                 {'type': 'links',
                  'heading': 'macroeconomics',
                  'items': [{'href': '/sections/macro', 'label': 'overview'},
                            {'href': '/sections/macro/inflation',
                             'label': 'inflation',
                             'meta': 'cpi, core cpi, pce, core pce, ppi'},
                            {'href': '/sections/macro/labor',
                             'label': 'labor',
                             'meta': 'unemployment, nonfarm payrolls, jobless claims, jolts, wage '
                                     'growth'},
                            {'href': '/sections/macro/growth',
                             'label': 'growth',
                             'meta': 'real gdp, retail sales, industrial production, housing '
                                     'starts'}]},
                 {'type': 'links',
                  'heading': 'interest rates &amp; credit',
                  'items': [{'href': '/sections/rates', 'label': 'overview'},
                            {'href': '/sections/rates/treasuries',
                             'label': 'policy &amp; treasuries',
                             'meta': 'fed funds, 2y, 10y, 30y, 10y&ndash;2y spread'},
                            {'href': '/sections/rates/credit',
                             'label': 'credit spreads',
                             'meta': 'investment grade, high yield'}]},
                 {'type': 'links',
                  'heading': 'market indexes',
                  'items': [{'href': '/sections/indexes', 'label': 'overview'},
                            {'href': '/sections/indexes/us',
                             'label': 'united states',
                             'meta': 's&amp;p 500, nasdaq composite, dow jones'},
                            {'href': '/sections/indexes/international',
                             'label': 'international',
                             'meta': 'nikkei 225, kospi, shanghai composite, hang seng, stoxx '
                                     'europe 600'}]},
                 {'type': 'links',
                  'heading': 'commodities &amp; materials',
                  'items': [{'href': '/sections/commodities',
                             'label': 'prices',
                             'meta': 'gold, silver, copper, aluminum, wti, brent, natural gas'}]},
                 {'type': 'links',
                  'heading': 'key companies',
                  'items': [{'href': '/sections/companies', 'label': 'overview'},
                            {'href': '/sections/companies/tech',
                             'label': 'technology / ai',
                             'meta': 'nvidia, microsoft, amazon, alphabet, apple, tsmc, asml'},
                            {'href': '/sections/companies/industrial',
                             'label': 'industrial',
                             'meta': 'caterpillar, deere, honeywell, ge aerospace, siemens'},
                            {'href': '/sections/companies/energy',
                             'label': 'energy',
                             'meta': 'exxonmobil, chevron, conocophillips, saudi aramco'},
                            {'href': '/sections/companies/financials',
                             'label': 'financials',
                             'meta': 'jpmorgan, bank of america, goldman sachs, berkshire'},
                            {'href': '/sections/companies/consumer',
                             'label': 'consumer',
                             'meta': "walmart, coca-cola, mcdonald's"}]},
                 {'type': 'links',
                  'heading': 'etfs',
                  'items': [{'href': '/sections/etfs', 'label': 'overview'},
                            {'href': '/sections/etfs/broad',
                             'label': 'broad market',
                             'meta': 'vti, voo, qqq, iwm, vt'},
                            {'href': '/sections/etfs/international',
                             'label': 'international',
                             'meta': 'vxus, eem'},
                            {'href': '/sections/etfs/materials',
                             'label': 'materials &amp; commodities',
                             'meta': 'remx, setm, copx, lit, ura, gdx, slv, pplt, pall'}]},
                 {'type': 'links',
                  'heading': 'trackers',
                  'items': [{'href': '/sections/ai-bubble', 'label': 'ai bubble tracker'},
                            {'href': '/sections/bitcoin', 'label': 'bitcoin'}]},
                 {'type': 'links',
                  'heading': 'relationships',
                  'items': [{'href': '/sections/relationships', 'label': 'economic relationships'},
                            {'text': 'inflation &rarr; interest rates &rarr; equities/credit'},
                            {'text': 'labor market &rarr; consumer spending &rarr; growth'},
                            {'text': 'interest rates &rarr; housing &rarr; '
                                     'construction/industrial'},
                            {'text': 'ai investment &rarr; semiconductors &rarr; electricity '
                                     '&rarr; commodities'},
                            {'text': 'china/global manufacturing &rarr; industrial metals &rarr; '
                                     'prices'},
                            {'text': 'geopolitics &rarr; energy/material supply &rarr; inflation'},
                            {'text': 'monetary policy &rarr; liquidity &rarr; financial markets'},
                            {'text': 'growth &rarr; industrial demand &rarr; commodities'}]}]},
 'sections/ai-bubble': {'title': 'ai bubble tracker',
                        'h1': 'AI Bubble Tracker',
                        'accent': 'violet',
                        'section': 'ai-bubble',
                        'tagline': 'where the money is going and what it is priced for',
                        'show_refreshed': True,
                        'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'ai bubble tracker'}],
                        'refresh': True,
                        'refresh_label': 'Refresh this page',
                        'summarize': True,
                        'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                        'panels': [{'type': 'metrics',
                                    'heading': 'concentration',
                                    'rows': [{'name': 'NVIDIA weight in S&amp;P 500',
                                              'derived': 'nvda-sp500-weight',
                                              'source': 'holdings'},
                                             {'name': 'Top 10 weight in S&amp;P 500',
                                              'derived': 'sp500-top10-weight',
                                              'source': 'holdings'},
                                             {'name': 'SPY &minus; RSP',
                                              'period': 'cap-weighted vs equal-weight, YTD',
                                              'derived': 'spy-rsp-ytd'},
                                             {'name': 'Nasdaq-100 P/E',
                                              'period': 'trailing &mdash; forward estimates are '
                                                        'licensed',
                                              'derived': 'ndx-trailing-pe'}]},
                                   {'type': 'note',
                                    'text': 'Empty &mdash; no ingest has run yet. Concentration is '
                                            'the single most direct bubble read: how much of the '
                                            'index is one trade.'},
                                   {'type': 'quotes',
                                    'heading': 'chips &amp; equipment',
                                    'columns': ['Company',
                                                'Ticker',
                                                'Mkt cap',
                                                '%',
                                                'S&amp;P weight'],
                                    'rows': [{'name': 'NVIDIA', 'symbol': 'NVDA', 'ticker': 'NVDA'},
                                             {'name': 'Broadcom',
                                              'symbol': 'AVGO',
                                              'ticker': 'AVGO'},
                                             {'name': 'AMD', 'symbol': 'AMD', 'ticker': 'AMD'},
                                             {'name': 'TSMC',
                                              'symbol': 'TSM',
                                              'unit': 'ADR',
                                              'ticker': 'TSM'},
                                             {'name': 'ASML',
                                              'symbol': 'ASML',
                                              'unit': 'ADR',
                                              'ticker': 'ASML'}]},
                                   {'type': 'quotes',
                                    'heading': 'buyers &middot; hyperscalers',
                                    'columns': ['Company', 'Ticker', 'Mkt cap', '%', 'Capex guide'],
                                    'rows': [{'name': 'Microsoft',
                                              'symbol': 'MSFT',
                                              'ticker': 'MSFT'},
                                             {'name': 'Alphabet',
                                              'symbol': 'GOOGL',
                                              'ticker': 'GOOGL'},
                                             {'name': 'Amazon', 'symbol': 'AMZN', 'ticker': 'AMZN'},
                                             {'name': 'Meta', 'symbol': 'META', 'ticker': 'META'},
                                             {'name': 'Oracle',
                                              'symbol': 'ORCL',
                                              'ticker': 'ORCL'}]},
                                   {'type': 'note',
                                    'text': 'Capex guidance is stated on quarterly earnings calls, '
                                            'not quoted &mdash; it updates four times a year, and '
                                            'it is the number that decides whether chip demand '
                                            'holds. Prices for the names also on <a '
                                            'href="/sections/companies/tech">companies / tech</a> '
                                            'live there; this page carries only what a sector page '
                                            'cannot show.'},
                                   {'type': 'quotes',
                                    'heading': 'buildout &amp; power',
                                    'columns': ['Company',
                                                'Ticker',
                                                'Mkt cap',
                                                '%',
                                                'S&amp;P weight'],
                                    'rows': [{'name': 'CoreWeave',
                                              'symbol': 'CRWV',
                                              'unit': 'GPU cloud',
                                              'ticker': 'CRWV'},
                                             {'name': 'Super Micro',
                                              'symbol': 'SMCI',
                                              'unit': 'servers',
                                              'ticker': 'SMCI'},
                                             {'name': 'Vertiv',
                                              'symbol': 'VRT',
                                              'unit': 'power &amp; cooling',
                                              'ticker': 'VRT'},
                                             {'name': 'Constellation Energy',
                                              'symbol': 'CEG',
                                              'unit': 'nuclear',
                                              'ticker': 'CEG'}]},
                                   {'type': 'metrics',
                                    'heading': 'private &middot; no ticker',
                                    'rows': [{'name': 'OpenAI',
                                              'period': 'last round valuation',
                                              'manual': 'news'},
                                             {'name': 'Anthropic',
                                              'period': 'last round valuation',
                                              'manual': 'news'},
                                             {'name': 'xAI',
                                              'period': 'last round valuation',
                                              'manual': 'news'}]},
                                   {'type': 'note',
                                    'text': 'No API carries these &mdash; private valuations only '
                                            'move when a round is announced, so they come from the '
                                            'news feed rather than an ingest job.'},
                                   {'type': 'links',
                                    'heading': 'circularity watch',
                                    'items': [{'text': 'chip vendors taking equity in their own '
                                                       'customers'},
                                              {'text': 'compute contracts counted as revenue by '
                                                       'both parties'},
                                              {'text': 'debt-funded datacenter buildout &mdash; '
                                                       'issuance and spreads'},
                                              {'text': 'capacity commitments announced without '
                                                       'named end demand'}]},
                                   {'type': 'note',
                                    'text': 'Qualitative, not a series. These are the patterns '
                                            'that separate a capex cycle from a bubble, and they '
                                            'surface in filings and reporting rather than in '
                                            'prices.'},
                                   {'type': 'links',
                                    'heading': 'downstream demand',
                                    'items': [{'href': '/sections/commodities',
                                               'label': 'natural gas',
                                               'meta': 'datacenter power'},
                                              {'href': '/sections/etfs/materials',
                                               'label': 'uranium',
                                               'meta': 'via URA &mdash; no free spot feed'},
                                              {'href': '/sections/commodities',
                                               'label': 'copper',
                                               'meta': 'grid and interconnect buildout'},
                                              {'href': '/sections/etfs/materials',
                                               'label': 'URA, SETM',
                                               'meta': 'tradeable proxies'}]},
                                   {'type': 'note',
                                    'text': 'Follows the chain in your notes: AI investment &rarr; '
                                            'semiconductors &rarr; electricity demand &rarr; '
                                            'commodities.'},
                                   {'type': 'stories',
                                    'heading': 'ai news',
                                    'items': [{}, {}, {}, {}]}]},
 'sections/bitcoin': {'title': 'bitcoin',
                      'h1': 'Bitcoin',
                      'accent': 'gold',
                      'section': 'bitcoin',
                      'tagline': 'trades continuously',
                      'show_refreshed': True,
                      'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'bitcoin'}],
                      'refresh': True,
                      'refresh_label': 'Refresh this page',
                      'summarize': True,
                      'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                      'panels': [{'type': 'quotes',
                                  'heading': 'price',
                                  'columns': ['Pair', 'Price', '24h', '%', 'YTD'],
                                  'rows': [{'name': 'Bitcoin',
                                            'symbol': 'BTC-USD',
                                            'unit': 'BTC / USD'}]},
                                 {'type': 'note',
                                  'text': 'Empty &mdash; no ingest has run yet. Bitcoin trades '
                                          '24/7, so the change column is a rolling 24 hours, not a '
                                          'session close like the equity pages.'},
                                 {'type': 'stories',
                                  'heading': 'related headlines',
                                  'items': [{}, {}, {}, {}]}]},
 'sections/commodities': {'title': 'commodities &amp; materials',
                          'h1': 'Commodities &amp; Materials',
                          'accent': 'clay',
                          'section': 'commodities',
                          'tagline': 'physical prices',
                          'show_refreshed': True,
                          'crumb': [{'href': '/', 'label': 'cobalt'},
                                    {'label': 'commodities &amp; materials'}],
                          'refresh': True,
                          'refresh_label': 'Refresh this page',
                          'summarize': True,
                          'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                          'panels': [{'type': 'quotes',
                                      'heading': 'precious',
                                      'columns': ['Metal', 'Price', 'Change', '%', 'YTD'],
                                      'rows': [{'name': 'Gold',
                                                'symbol': 'GC=F',
                                                'unit': 'USD / troy oz'},
                                               {'name': 'Silver',
                                                'symbol': 'SI=F',
                                                'unit': 'USD / troy oz'}],
                                      'source': 'yahoo'},
                                     {'type': 'metrics',
                                      'rows': [{'name': 'Gold / silver ratio',
                                                'period': 'ounces of silver per ounce of gold',
                                                'derived': 'gold-silver-ratio'}]},
                                     {'type': 'quotes',
                                      'heading': 'industrial',
                                      'columns': ['Metal', 'Price', 'Change', '%', 'YTD'],
                                      'rows': [{'name': 'Copper',
                                                'symbol': 'HG=F',
                                                'unit': 'USD / lb'},
                                               {'name': 'Aluminum',
                                                'symbol': 'ALI=F',
                                                'unit': 'USD / tonne'}],
                                      'source': 'yahoo'},
                                     {'type': 'quotes',
                                      'heading': 'energy',
                                      'columns': ['Contract', 'Price', 'Change', '%', 'YTD'],
                                      'rows': [{'name': 'WTI crude',
                                                'symbol': 'CL=F',
                                                'unit': 'USD / bbl'},
                                               {'name': 'Brent crude',
                                                'symbol': 'BZ=F',
                                                'unit': 'USD / bbl'},
                                               {'name': 'Natural gas',
                                                'symbol': 'NG=F',
                                                'unit': 'USD / MMBtu'}],
                                      'source': 'yahoo'},
                                     {'type': 'metrics',
                                      'rows': [{'name': 'Brent &ndash; WTI',
                                                'period': 'USD / bbl',
                                                'derived': 'brent-wti-spread'}]},
                                     {'type': 'note',
                                      'text': 'Empty &mdash; no ingest has run yet. Aluminum '
                                              'trades thinly and its quote can lag the others by a '
                                              'session.'},
                                     {'type': 'links',
                                      'heading': 'not priced here',
                                      'items': [{'text': 'tungsten, uranium, lithium, cobalt, iron '
                                                         'ore, nickel'},
                                                {'href': '/sections/etfs/materials',
                                                 'label': 'tracked via materials ETFs',
                                                 'meta': 'no free spot feed exists for these'}]},
                                     {'type': 'stories',
                                      'heading': 'related headlines',
                                      'items': [{}, {}],
                                      'tags': 'gold,silver,copper,oil,natural-gas'}]},
 'sections/companies/consumer': {'title': 'consumer',
                                 'h1': 'Consumer',
                                 'section': 'companies',
                                 'tagline': 'household demand and pricing power',
                                 'show_refreshed': True,
                                 'crumb': [{'href': '/', 'label': 'cobalt'},
                                           {'href': '/sections/companies',
                                            'label': 'key companies'},
                                           {'label': 'consumer'}],
                                 'refresh': True,
                                 'refresh_label': 'Refresh this page',
                                 'summarize': True,
                                 'summary_body': 'No summary yet. Refresh the data, then ask for '
                                                 'one.',
                                 'panels': [{'type': 'quotes',
                                             'heading': 'companies',
                                             'columns': ['Company',
                                                         'Ticker',
                                                         'Price',
                                                         'Change',
                                                         '%',
                                                         'Mkt cap'],
                                             'rows': [{'name': 'Walmart',
                                                       'symbol': 'WMT',
                                                       'ticker': 'WMT'},
                                                      {'name': 'Coca-Cola',
                                                       'symbol': 'KO',
                                                       'ticker': 'KO'},
                                                      {'name': "McDonald's",
                                                       'symbol': 'MCD',
                                                       'ticker': 'MCD'}]},
                                            {'type': 'note',
                                             'text': 'Empty &mdash; no ingest has run yet. Source '
                                                     'and quote time appear here.'},
                                            {'type': 'stories',
                                             'heading': 'related headlines',
                                             'items': [{}, {}]}]},
 'sections/companies/energy': {'title': 'energy companies',
                               'h1': 'Energy',
                               'section': 'companies',
                               'tagline': '',
                               'show_refreshed': True,
                               'crumb': [{'href': '/', 'label': 'cobalt'},
                                         {'href': '/sections/companies', 'label': 'key companies'},
                                         {'label': 'energy'}],
                               'refresh': True,
                               'refresh_label': 'Refresh this page',
                               'summarize': True,
                               'summary_body': 'No summary yet. Refresh the data, then ask for '
                                               'one.',
                               'panels': [{'type': 'quotes',
                                           'heading': 'us majors',
                                           'columns': ['Company',
                                                       'Ticker',
                                                       'Price',
                                                       'Change',
                                                       '%',
                                                       'Mkt cap'],
                                           'rows': [{'name': 'ExxonMobil',
                                                     'symbol': 'XOM',
                                                     'ticker': 'XOM'},
                                                    {'name': 'Chevron',
                                                     'symbol': 'CVX',
                                                     'ticker': 'CVX'},
                                                    {'name': 'ConocoPhillips',
                                                     'symbol': 'COP',
                                                     'ticker': 'COP'}]},
                                          {'type': 'quotes',
                                           'heading': 'international',
                                           'columns': ['Company',
                                                       'Ticker',
                                                       'Price',
                                                       'Change',
                                                       '%',
                                                       'Mkt cap'],
                                           'rows': [{'name': 'Saudi Aramco',
                                                     'symbol': '2222.SR',
                                                     'unit': 'SAR &middot; Tadawul',
                                                     'ticker': '2222.SR'}]},
                                          {'type': 'note',
                                           'text': 'Empty &mdash; no ingest has run yet. Aramco '
                                                   'has no US listing &mdash; it prices in riyals '
                                                   'on the Tadawul, which runs Sunday to Thursday, '
                                                   'so its week does not line up with the US '
                                                   'majors above.'},
                                          {'type': 'stories',
                                           'heading': 'related headlines',
                                           'items': [{}, {}]}]},
 'sections/companies/financials': {'title': 'financials',
                                   'h1': 'Financials',
                                   'section': 'companies',
                                   'tagline': 'credit conditions and risk appetite',
                                   'show_refreshed': True,
                                   'crumb': [{'href': '/', 'label': 'cobalt'},
                                             {'href': '/sections/companies',
                                              'label': 'key companies'},
                                             {'label': 'financials'}],
                                   'refresh': True,
                                   'refresh_label': 'Refresh this page',
                                   'summarize': True,
                                   'summary_body': 'No summary yet. Refresh the data, then ask for '
                                                   'one.',
                                   'panels': [{'type': 'quotes',
                                               'heading': 'companies',
                                               'columns': ['Company',
                                                           'Ticker',
                                                           'Price',
                                                           'Change',
                                                           '%',
                                                           'Mkt cap'],
                                               'rows': [{'name': 'JPMorgan Chase',
                                                         'symbol': 'JPM',
                                                         'ticker': 'JPM'},
                                                        {'name': 'Bank of America',
                                                         'symbol': 'BAC',
                                                         'ticker': 'BAC'},
                                                        {'name': 'Goldman Sachs',
                                                         'symbol': 'GS',
                                                         'ticker': 'GS'},
                                                        {'name': 'Berkshire Hathaway',
                                                         'symbol': 'BRK-B',
                                                         'unit': 'class B',
                                                         'ticker': 'BRK-B'}]},
                                              {'type': 'note',
                                               'text': 'Empty &mdash; no ingest has run yet. '
                                                       'Berkshire is tracked on the class B share; '
                                                       'class A (BRK-A) is the same company at '
                                                       'roughly 1,500&times; the price per share.'},
                                              {'type': 'stories',
                                               'heading': 'related headlines',
                                               'items': [{}, {}]}]},
 'sections/companies': {'title': 'key companies',
                        'h1': 'Key Companies',
                        'section': 'companies',
                        'tagline': 'bellwethers by sector',
                        'show_refreshed': True,
                        'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'key companies'}],
                        'refresh': True,
                        'refresh_label': 'Refresh this page',
                        'summarize': True,
                        'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                        'panels': [{'type': 'links',
                                    'heading': 'sectors',
                                    'items': [{'href': '/sections/companies/tech',
                                               'label': 'technology / ai',
                                               'meta': 'nvidia, microsoft, amazon, alphabet, '
                                                       'apple, tsmc, asml'},
                                              {'href': '/sections/companies/industrial',
                                               'label': 'industrial',
                                               'meta': 'caterpillar, deere, honeywell, ge '
                                                       'aerospace, siemens'},
                                              {'href': '/sections/companies/energy',
                                               'label': 'energy',
                                               'meta': 'exxonmobil, chevron, conocophillips, saudi '
                                                       'aramco'},
                                              {'href': '/sections/companies/financials',
                                               'label': 'financials',
                                               'meta': 'jpmorgan, bank of america, goldman sachs, '
                                                       'berkshire'},
                                              {'href': '/sections/companies/consumer',
                                               'label': 'consumer',
                                               'meta': "walmart, coca-cola, mcdonald's"}]},
                                   {'type': 'note',
                                    'text': 'This page is an index. Figures live on the pages '
                                            'above; refreshing here refreshes all of them.'}]},
 'sections/companies/industrial': {'title': 'industrial',
                                   'h1': 'Industrial',
                                   'section': 'companies',
                                   'tagline': 'construction, agriculture, aerospace',
                                   'show_refreshed': True,
                                   'crumb': [{'href': '/', 'label': 'cobalt'},
                                             {'href': '/sections/companies',
                                              'label': 'key companies'},
                                             {'label': 'industrial'}],
                                   'refresh': True,
                                   'refresh_label': 'Refresh this page',
                                   'summarize': True,
                                   'summary_body': 'No summary yet. Refresh the data, then ask for '
                                                   'one.',
                                   'panels': [{'type': 'quotes',
                                               'heading': 'companies',
                                               'columns': ['Company',
                                                           'Ticker',
                                                           'Price',
                                                           'Change',
                                                           '%',
                                                           'Mkt cap'],
                                               'rows': [{'name': 'Caterpillar',
                                                         'symbol': 'CAT',
                                                         'ticker': 'CAT'},
                                                        {'name': 'Deere',
                                                         'symbol': 'DE',
                                                         'ticker': 'DE'},
                                                        {'name': 'Honeywell',
                                                         'symbol': 'HON',
                                                         'ticker': 'HON'},
                                                        {'name': 'GE Aerospace',
                                                         'symbol': 'GE',
                                                         'ticker': 'GE'},
                                                        {'name': 'Siemens',
                                                         'symbol': 'SIEGY',
                                                         'unit': 'ADR',
                                                         'ticker': 'SIEGY'}]},
                                              {'type': 'note',
                                               'text': 'Empty &mdash; no ingest has run yet. '
                                                       'Siemens is quoted as the US ADR; the '
                                                       'primary listing is SIE.DE on XETRA in '
                                                       'euros.'},
                                              {'type': 'stories',
                                               'heading': 'related headlines',
                                               'items': [{}, {}]}]},
 'sections/companies/tech': {'title': 'technology / ai',
                             'h1': 'Technology / AI',
                             'section': 'companies',
                             'tagline': '',
                             'show_refreshed': True,
                             'crumb': [{'href': '/', 'label': 'cobalt'},
                                       {'href': '/sections/companies', 'label': 'key companies'},
                                       {'label': 'technology / ai'}],
                             'refresh': True,
                             'refresh_label': 'Refresh this page',
                             'summarize': True,
                             'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                             'panels': [{'type': 'quotes',
                                         'heading': 'platforms',
                                         'columns': ['Company',
                                                     'Ticker',
                                                     'Price',
                                                     'Change',
                                                     '%',
                                                     'Mkt cap'],
                                         'rows': [{'name': 'Microsoft',
                                                   'symbol': 'MSFT',
                                                   'ticker': 'MSFT'},
                                                  {'name': 'Amazon',
                                                   'symbol': 'AMZN',
                                                   'ticker': 'AMZN'},
                                                  {'name': 'Alphabet',
                                                   'symbol': 'GOOGL',
                                                   'ticker': 'GOOGL'},
                                                  {'name': 'Apple',
                                                   'symbol': 'AAPL',
                                                   'ticker': 'AAPL'}]},
                                        {'type': 'quotes',
                                         'heading': 'semiconductors',
                                         'columns': ['Company',
                                                     'Ticker',
                                                     'Price',
                                                     'Change',
                                                     '%',
                                                     'Mkt cap'],
                                         'rows': [{'name': 'NVIDIA',
                                                   'symbol': 'NVDA',
                                                   'ticker': 'NVDA'},
                                                  {'name': 'TSMC',
                                                   'symbol': 'TSM',
                                                   'unit': 'ADR',
                                                   'ticker': 'TSM'},
                                                  {'name': 'ASML',
                                                   'symbol': 'ASML',
                                                   'unit': 'ADR',
                                                   'ticker': 'ASML'}]},
                                        {'type': 'note',
                                         'text': 'Empty &mdash; no ingest has run yet. TSMC and '
                                                 'ASML are quoted here as US-listed ADRs, so they '
                                                 'price in USD on US hours &mdash; their home '
                                                 'listings in Taipei and Amsterdam move first.'},
                                        {'type': 'stories',
                                         'heading': 'related headlines',
                                         'items': [{}, {}]}]},
 'sections/etfs/broad': {'title': 'broad market etfs',
                         'h1': 'Broad Market',
                         'section': 'etfs',
                         'tagline': '',
                         'show_refreshed': True,
                         'crumb': [{'href': '/', 'label': 'cobalt'},
                                   {'href': '/sections/etfs', 'label': 'etfs'},
                                   {'label': 'broad market'}],
                         'refresh': True,
                         'refresh_label': 'Refresh this page',
                         'summarize': True,
                         'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                         'panels': [{'type': 'quotes',
                                     'heading': 'funds',
                                     'columns': ['Fund', 'Ticker', 'Price', 'Change', '%', 'YTD'],
                                     'rows': [{'name': 'US total market',
                                               'symbol': 'VTI',
                                               'unit': 'Vanguard',
                                               'ticker': 'VTI'},
                                              {'name': 'S&amp;P 500',
                                               'symbol': 'VOO',
                                               'unit': 'Vanguard',
                                               'ticker': 'VOO'},
                                              {'name': 'Nasdaq-100',
                                               'symbol': 'QQQ',
                                               'unit': 'Invesco',
                                               'ticker': 'QQQ'},
                                              {'name': 'Russell 2000',
                                               'symbol': 'IWM',
                                               'unit': 'small cap',
                                               'ticker': 'IWM'},
                                              {'name': 'Global equities',
                                               'symbol': 'VT',
                                               'unit': 'Vanguard',
                                               'ticker': 'VT'}]},
                                    {'type': 'metrics',
                                     'heading': 'breadth',
                                     'rows': [{'name': 'QQQ &minus; IWM',
                                               'period': 'large-cap tech vs small caps, YTD',
                                               'derived': 'qqq-iwm-ytd'}]},
                                    {'type': 'note',
                                     'text': 'Empty &mdash; no ingest has run yet. VTI and VOO '
                                             'overlap heavily &mdash; the S&amp;P 500 is most of '
                                             'the US market by weight &mdash; so a gap between '
                                             'them is a small-cap signal.'},
                                    {'type': 'stories',
                                     'heading': 'related headlines',
                                     'items': [{}, {}]}]},
 'sections/etfs': {'title': 'etfs',
                   'h1': 'ETFs',
                   'section': 'etfs',
                   'tagline': 'sector, asset-class and commodity indicators',
                   'show_refreshed': True,
                   'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'etfs'}],
                   'refresh': True,
                   'refresh_label': 'Refresh this page',
                   'summarize': True,
                   'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                   'panels': [{'type': 'links',
                               'heading': 'sections',
                               'items': [{'href': '/sections/etfs/broad',
                                          'label': 'broad market',
                                          'meta': 'vti, voo, qqq, iwm, vt'},
                                         {'href': '/sections/etfs/international',
                                          'label': 'international',
                                          'meta': 'vxus, eem'},
                                         {'href': '/sections/etfs/materials',
                                          'label': 'materials &amp; commodities',
                                          'meta': 'remx, setm, copx, lit, ura, gdx, slv, pplt, '
                                                  'pall'}]},
                              {'type': 'note',
                               'text': 'This page is an index. Figures live on the pages above; '
                                       'refreshing here refreshes all of them.'}]},
 'sections/etfs/international': {'title': 'international etfs',
                                 'h1': 'International',
                                 'section': 'etfs',
                                 'tagline': '',
                                 'show_refreshed': True,
                                 'crumb': [{'href': '/', 'label': 'cobalt'},
                                           {'href': '/sections/etfs', 'label': 'etfs'},
                                           {'label': 'international'}],
                                 'refresh': True,
                                 'refresh_label': 'Refresh this page',
                                 'summarize': True,
                                 'summary_body': 'No summary yet. Refresh the data, then ask for '
                                                 'one.',
                                 'panels': [{'type': 'quotes',
                                             'heading': 'funds',
                                             'columns': ['Fund',
                                                         'Ticker',
                                                         'Price',
                                                         'Change',
                                                         '%',
                                                         'YTD'],
                                             'rows': [{'name': 'International ex-US',
                                                       'symbol': 'VXUS',
                                                       'unit': 'Vanguard',
                                                       'ticker': 'VXUS'},
                                                      {'name': 'Emerging markets',
                                                       'symbol': 'EEM',
                                                       'unit': 'iShares',
                                                       'ticker': 'EEM'}]},
                                            {'type': 'note',
                                             'text': 'Empty &mdash; no ingest has run yet. Both '
                                                     'hold assets priced in other currencies but '
                                                     'trade in USD, so their moves blend local '
                                                     'performance with the dollar &mdash; a strong '
                                                     'dollar drags returns even when the '
                                                     'underlying markets rise.'},
                                            {'type': 'stories',
                                             'heading': 'related headlines',
                                             'items': [{}, {}]}]},
 'sections/etfs/materials': {'title': 'materials etfs',
                             'h1': 'Materials &amp; Commodities',
                             'section': 'etfs',
                             'tagline': 'also the free proxy for unpriced metals',
                             'show_refreshed': True,
                             'crumb': [{'href': '/', 'label': 'cobalt'},
                                       {'href': '/sections/etfs', 'label': 'etfs'},
                                       {'label': 'materials &amp; commodities'}],
                             'refresh': True,
                             'refresh_label': 'Refresh this page',
                             'summarize': True,
                             'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                             'panels': [{'type': 'quotes',
                                         'heading': 'physically backed',
                                         'columns': ['Fund',
                                                     'Ticker',
                                                     'Price',
                                                     'Change',
                                                     '%',
                                                     'YTD'],
                                         'rows': [{'name': 'Silver',
                                                   'symbol': 'SLV',
                                                   'unit': 'holds metal',
                                                   'ticker': 'SLV'},
                                                  {'name': 'Platinum',
                                                   'symbol': 'PPLT',
                                                   'unit': 'holds metal',
                                                   'ticker': 'PPLT'},
                                                  {'name': 'Palladium',
                                                   'symbol': 'PALL',
                                                   'unit': 'holds metal',
                                                   'ticker': 'PALL'}]},
                                        {'type': 'quotes',
                                         'heading': 'miner &amp; producer baskets',
                                         'columns': ['Fund',
                                                     'Ticker',
                                                     'Price',
                                                     'Change',
                                                     '%',
                                                     'YTD'],
                                         'rows': [{'name': 'Gold miners',
                                                   'symbol': 'GDX',
                                                   'ticker': 'GDX'},
                                                  {'name': 'Copper miners',
                                                   'symbol': 'COPX',
                                                   'ticker': 'COPX'},
                                                  {'name': 'Rare earths &amp; strategic metals',
                                                   'symbol': 'REMX',
                                                   'ticker': 'REMX'},
                                                  {'name': 'Critical materials',
                                                   'symbol': 'SETM',
                                                   'ticker': 'SETM'},
                                                  {'name': 'Lithium &amp; battery technology',
                                                   'symbol': 'LIT',
                                                   'ticker': 'LIT'},
                                                  {'name': 'Uranium',
                                                   'symbol': 'URA',
                                                   'ticker': 'URA'}]},
                                        {'type': 'note',
                                         'text': 'Empty &mdash; no ingest has run yet. The split '
                                                 'matters when these stand in for <a '
                                                 'href="/sections/commodities">spot prices</a>: '
                                                 'the physically backed trusts track metal almost '
                                                 'one-for-one, while the miner baskets carry '
                                                 'equity risk and operating leverage, so they '
                                                 'overshoot the commodity in both directions. LIT, '
                                                 'URA, REMX and SETM are the practical proxies for '
                                                 'lithium, uranium, tungsten and cobalt, none of '
                                                 'which have a free spot feed.'},
                                        {'type': 'stories',
                                         'heading': 'related headlines',
                                         'items': [{}, {}]}]},
 'sections/indexes': {'title': 'market indexes',
                      'h1': 'Market Indexes',
                      'section': 'indexes',
                      'tagline': 'major equity markets',
                      'show_refreshed': True,
                      'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'market indexes'}],
                      'refresh': True,
                      'refresh_label': 'Refresh this page',
                      'summarize': True,
                      'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                      'panels': [{'type': 'links',
                                  'heading': 'sections',
                                  'items': [{'href': '/sections/indexes/us',
                                             'label': 'united states',
                                             'meta': 's&amp;p 500, nasdaq, dow'},
                                            {'href': '/sections/indexes/international',
                                             'label': 'international',
                                             'meta': 'japan, korea, china, hong kong, europe'}]},
                                 {'type': 'note',
                                  'text': 'This page is an index. Figures live on the pages above; '
                                          'refreshing here refreshes all of them.'}]},
 'sections/indexes/international': {'title': 'international indexes',
                                    'h1': 'International',
                                    'section': 'indexes',
                                    'tagline': '',
                                    'show_refreshed': True,
                                    'crumb': [{'href': '/', 'label': 'cobalt'},
                                              {'href': '/sections/indexes',
                                               'label': 'market indexes'},
                                              {'label': 'international'}],
                                    'refresh': True,
                                    'refresh_label': 'Refresh this page',
                                    'summarize': True,
                                    'summary_body': 'No summary yet. Refresh the data, then ask '
                                                    'for one.',
                                    'panels': [{'type': 'quotes',
                                                'heading': 'asia-pacific',
                                                'columns': ['Index',
                                                            'Level',
                                                            'Change',
                                                            '%',
                                                            'As of'],
                                                'rows': [{'name': 'Nikkei 225',
                                                          'symbol': '^N225',
                                                          'region': 'Japan',
                                                          'session': True},
                                                         {'name': 'KOSPI',
                                                          'symbol': '^KS11',
                                                          'region': 'South Korea',
                                                          'session': True},
                                                         {'name': 'Shanghai Composite',
                                                          'symbol': '000001.SS',
                                                          'region': 'China',
                                                          'session': True},
                                                         {'name': 'Hang Seng',
                                                          'symbol': '^HSI',
                                                          'region': 'Hong Kong',
                                                          'session': True}]},
                                               {'type': 'quotes',
                                                'heading': 'europe',
                                                'columns': ['Index',
                                                            'Level',
                                                            'Change',
                                                            '%',
                                                            'As of'],
                                                'rows': [{'name': 'STOXX Europe 600',
                                                          'symbol': '^STOXX',
                                                          'region': 'Europe',
                                                          'session': True}]},
                                               {'type': 'note',
                                                'text': 'Empty &mdash; no ingest has run yet. '
                                                        'These markets close before US hours, so '
                                                        'most quotes will be a prior close &mdash; '
                                                        'the dot and &ldquo;as of&rdquo; column '
                                                        'say which.'},
                                               {'type': 'stories',
                                                'heading': 'related headlines',
                                                'items': [{}, {}]}]},
 'sections/indexes/us': {'title': 'us indexes',
                         'h1': 'United States',
                         'section': 'indexes',
                         'tagline': '',
                         'show_refreshed': True,
                         'crumb': [{'href': '/', 'label': 'cobalt'},
                                   {'href': '/sections/indexes', 'label': 'market indexes'},
                                   {'label': 'united states'}],
                         'refresh': True,
                         'refresh_label': 'Refresh this page',
                         'summarize': True,
                         'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                         'panels': [{'type': 'quotes',
                                     'heading': 'indexes',
                                     'columns': ['Index', 'Level', 'Change', '%', 'YTD'],
                                     'rows': [{'name': 'S&amp;P 500',
                                               'symbol': '^GSPC',
                                               'session': True},
                                              {'name': 'Nasdaq Composite',
                                               'symbol': '^IXIC',
                                               'session': True},
                                              {'name': 'Dow Jones Industrial Average',
                                               'symbol': '^DJI',
                                               'session': True}]},
                                    {'type': 'note',
                                     'text': 'Empty &mdash; no ingest has run yet. Dot shows '
                                             'whether the market was open at refresh.'},
                                    {'type': 'stories',
                                     'heading': 'related headlines',
                                     'items': [{}, {}]}]},
 'sections/macro/growth': {'title': 'growth',
                           'h1': 'Growth',
                           'accent': 'green',
                           'section': 'macro',
                           'tagline': '',
                           'show_refreshed': True,
                           'crumb': [{'href': '/', 'label': 'cobalt'},
                                     {'href': '/sections/macro', 'label': 'macroeconomics'},
                                     {'label': 'growth'}],
                           'refresh': True,
                           'refresh_label': 'Refresh this page',
                           'summarize': True,
                           'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                           'panels': [{'type': 'metrics',
                                       'heading': 'series',
                                       'rows': [{'name': 'Real GDP',
                                                 'period': 'quarterly, annualized',
                                                 'series': 'GDPC1'},
                                                {'name': 'Retail sales',
                                                 'period': 'monthly change',
                                                 'series': 'RSAFS'},
                                                {'name': 'Industrial production',
                                                 'period': 'monthly change',
                                                 'series': 'INDPRO'},
                                                {'name': 'Housing starts',
                                                 'period': 'annualized',
                                                 'series': 'HOUST'}]},
                                      {'type': 'note',
                                       'text': 'Empty &mdash; no ingest has run yet. No survey '
                                               'data: ISM PMI is licensed and has no free feed, so '
                                               'growth here is read from hard data only, which '
                                               'lags.'},
                                      {'type': 'stories',
                                       'heading': 'related headlines',
                                       'items': [{}, {}]}]},
 'sections/macro': {'title': 'macroeconomics',
                    'h1': 'Macroeconomics',
                    'accent': 'green',
                    'section': 'macro',
                    'tagline': 'health and direction of the economy',
                    'show_refreshed': True,
                    'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'macroeconomics'}],
                    'refresh': True,
                    'refresh_label': 'Refresh this page',
                    'summarize': True,
                    'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                    'panels': [{'type': 'links',
                                'heading': 'sections',
                                'items': [{'href': '/sections/macro/inflation',
                                           'label': 'inflation',
                                           'meta': 'cpi, core cpi, pce, core pce, ppi'},
                                          {'href': '/sections/macro/labor',
                                           'label': 'labor',
                                           'meta': 'unemployment, payrolls, claims, jolts, wages'},
                                          {'href': '/sections/macro/growth',
                                           'label': 'growth',
                                           'meta': 'gdp, retail sales, production, pmi, housing'}]},
                               {'type': 'note',
                                'text': 'This page is an index. Figures live on the pages above; '
                                        'refreshing here refreshes all of them.'}]},
 'sections/macro/inflation': {'title': 'inflation',
                              'h1': 'Inflation',
                              'accent': 'green',
                              'section': 'macro',
                              'tagline': '',
                              'show_refreshed': True,
                              'crumb': [{'href': '/', 'label': 'cobalt'},
                                        {'href': '/sections/macro', 'label': 'macroeconomics'},
                                        {'label': 'inflation'}],
                              'refresh': True,
                              'refresh_label': 'Refresh this page',
                              'summarize': True,
                              'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                              'panels': [{'type': 'metrics',
                                          'heading': 'series',
                                          'rows': [{'name': 'CPI',
                                                    'period': 'year over year',
                                                    'series': 'CPIAUCSL'},
                                                   {'name': 'Core CPI',
                                                    'period': 'year over year',
                                                    'series': 'CPILFESL'},
                                                   {'name': 'PCE',
                                                    'period': 'year over year',
                                                    'series': 'PCEPI'},
                                                   {'name': 'Core PCE',
                                                    'period': 'year over year',
                                                    'series': 'PCEPILFE'},
                                                   {'name': 'PPI',
                                                    'period': 'year over year',
                                                    'series': 'PPIFIS'}]},
                                         {'type': 'note',
                                          'text': 'Empty &mdash; no ingest has run yet. Source and '
                                                  'release date appear here.'},
                                         {'type': 'stories',
                                          'heading': 'related headlines',
                                          'items': [{}, {}]}]},
 'sections/macro/labor': {'title': 'labor',
                          'h1': 'Labor',
                          'accent': 'green',
                          'section': 'macro',
                          'tagline': '',
                          'show_refreshed': True,
                          'crumb': [{'href': '/', 'label': 'cobalt'},
                                    {'href': '/sections/macro', 'label': 'macroeconomics'},
                                    {'label': 'labor'}],
                          'refresh': True,
                          'refresh_label': 'Refresh this page',
                          'summarize': True,
                          'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                          'panels': [{'type': 'metrics',
                                      'heading': 'series',
                                      'rows': [{'name': 'Unemployment rate', 'series': 'UNRATE'},
                                               {'name': 'Nonfarm payrolls',
                                                'period': 'monthly change',
                                                'series': 'PAYEMS'},
                                               {'name': 'Initial jobless claims',
                                                'period': 'weekly',
                                                'series': 'ICSA'},
                                               {'name': 'JOLTS job openings', 'series': 'JTSJOL'},
                                               {'name': 'Wage growth',
                                                'period': 'year over year',
                                                'series': 'CES0500000003'}]},
                                     {'type': 'note',
                                      'text': 'Empty &mdash; no ingest has run yet. Source and '
                                              'release date appear here.'},
                                     {'type': 'stories',
                                      'heading': 'related headlines',
                                      'items': [{}, {}]}]},
 'sections/news/economics': {'title': 'economics news',
                             'h1': 'Economics',
                             'accent': 'green',
                             'section': 'news',
                             'tagline': 'markets, policy, macro',
                             'show_refreshed': True,
                             'crumb': [{'href': '/', 'label': 'cobalt'},
                                       {'href': '/sections/news', 'label': 'news'},
                                       {'label': 'economics'}],
                             'refresh': True,
                             'refresh_label': 'Refresh this page',
                             'summarize': True,
                             'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                             'panels': [{'type': 'stories',
                                         'heading': 'headlines',
                                         'items': [{}, {}, {}, {}]},
                                        {'type': 'note',
                                         'style': 'meta',
                                         'text': 'Empty &mdash; no ingest has run yet.'}]},
 'sections/news': {'title': 'news',
                   'h1': 'News',
                   'section': 'news',
                   'tagline': 'all sections',
                   'show_refreshed': True,
                   'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'news'}],
                   'refresh': True,
                   'refresh_label': 'Refresh this page',
                   'summarize': True,
                   'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                   'panels': [{'type': 'links',
                               'heading': 'sections',
                               'items': [{'href': '/sections/news/politics', 'label': 'politics'},
                                         {'href': '/sections/news/economics', 'label': 'economics'},
                                         {'href': '/sections/news/tech',
                                          'label': 'technology &amp; science'}]},
                              {'type': 'stories',
                               'heading': 'latest headlines',
                               'items': [{'tag': 'politics', 'tag_class': 'tag-politics'},
                                         {'tag': 'economics', 'tag_class': 'tag-economics'},
                                         {'tag': 'tech', 'tag_class': 'tag-tech'}]},
                              {'type': 'note',
                               'style': 'meta',
                               'text': 'Empty &mdash; no ingest has run yet.'}]},
 'sections/news/politics': {'title': 'politics',
                            'h1': 'Politics',
                            'accent': 'clay',
                            'section': 'news',
                            'tagline': 'primarily US',
                            'show_refreshed': True,
                            'crumb': [{'href': '/', 'label': 'cobalt'},
                                      {'href': '/sections/news', 'label': 'news'},
                                      {'label': 'politics'}],
                            'refresh': True,
                            'refresh_label': 'Refresh this page',
                            'summarize': True,
                            'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                            'panels': [{'type': 'stories',
                                        'heading': 'headlines',
                                        'items': [{}, {}, {}, {}]},
                                       {'type': 'note',
                                        'style': 'meta',
                                        'text': 'Empty &mdash; no ingest has run yet.'}]},
 'sections/news/tech': {'title': 'technology &amp; science',
                        'h1': 'Technology &amp; Science',
                        'accent': 'violet',
                        'section': 'news',
                        'tagline': '',
                        'show_refreshed': True,
                        'crumb': [{'href': '/', 'label': 'cobalt'},
                                  {'href': '/sections/news', 'label': 'news'},
                                  {'label': 'technology &amp; science'}],
                        'refresh': True,
                        'refresh_label': 'Refresh this page',
                        'summarize': True,
                        'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                        'panels': [{'type': 'stories',
                                    'heading': 'headlines',
                                    'items': [{}, {}, {}, {}]},
                                   {'type': 'note',
                                    'style': 'meta',
                                    'text': 'Empty &mdash; no ingest has run yet.'}]},
 'sections/rates/credit': {'title': 'credit spreads',
                           'h1': 'Credit Spreads',
                           'accent': 'green',
                           'section': 'rates',
                           'tagline': 'availability and price of credit',
                           'show_refreshed': True,
                           'crumb': [{'href': '/', 'label': 'cobalt'},
                                     {'href': '/sections/rates',
                                      'label': 'interest rates &amp; credit'},
                                     {'label': 'credit spreads'}],
                           'refresh': True,
                           'refresh_label': 'Refresh this page',
                           'summarize': True,
                           'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                           'panels': [{'type': 'metrics',
                                       'heading': 'spreads',
                                       'rows': [{'name': 'Investment grade',
                                                 'period': 'option-adjusted, bps',
                                                 'series': 'BAMLC0A0CM'},
                                                {'name': 'High yield',
                                                 'period': 'option-adjusted, bps',
                                                 'series': 'BAMLH0A0HYM2'}]},
                                      {'type': 'note',
                                       'text': 'Empty &mdash; no ingest has run yet. Source and '
                                               'release date appear here. Widening spreads signal '
                                               'tightening credit conditions.'},
                                      {'type': 'stories',
                                       'heading': 'related headlines',
                                       'items': [{}, {}]}]},
 'sections/rates': {'title': 'interest rates &amp; credit',
                    'h1': 'Interest Rates &amp; Credit',
                    'accent': 'green',
                    'section': 'rates',
                    'tagline': 'monetary policy and the cost of capital',
                    'show_refreshed': True,
                    'crumb': [{'href': '/', 'label': 'cobalt'},
                              {'label': 'interest rates &amp; credit'}],
                    'refresh': True,
                    'refresh_label': 'Refresh this page',
                    'summarize': True,
                    'summary_body': 'No summary yet. Refresh the data, then ask for one.',
                    'panels': [{'type': 'links',
                                'heading': 'sections',
                                'items': [{'href': '/sections/rates/treasuries',
                                           'label': 'policy &amp; treasuries',
                                           'meta': 'fed funds, 2y, 10y, 30y, curve'},
                                          {'href': '/sections/rates/credit',
                                           'label': 'credit spreads',
                                           'meta': 'investment grade, high yield'}]},
                               {'type': 'note',
                                'text': 'This page is an index. Figures live on the pages above; '
                                        'refreshing here refreshes all of them.'}]},
 'sections/rates/treasuries': {'title': 'policy &amp; treasuries',
                               'h1': 'Policy &amp; Treasuries',
                               'accent': 'green',
                               'section': 'rates',
                               'tagline': '',
                               'show_refreshed': True,
                               'crumb': [{'href': '/', 'label': 'cobalt'},
                                         {'href': '/sections/rates',
                                          'label': 'interest rates &amp; credit'},
                                         {'label': 'policy &amp; treasuries'}],
                               'refresh': True,
                               'refresh_label': 'Refresh this page',
                               'summarize': True,
                               'summary_body': 'No summary yet. Refresh the data, then ask for '
                                               'one.',
                               'panels': [{'type': 'metrics',
                                           'heading': 'policy rate',
                                           'rows': [{'name': 'Federal Funds Rate',
                                                     'period': 'upper bound',
                                                     'series': 'FEDFUNDS'}]},
                                          {'type': 'metrics',
                                           'heading': 'treasury yields',
                                           'rows': [{'name': '2-Year Treasury', 'series': 'DGS2'},
                                                    {'name': '10-Year Treasury', 'series': 'DGS10'},
                                                    {'name': '30-Year Treasury',
                                                     'series': 'DGS30'}]},
                                          {'type': 'metrics',
                                           'heading': 'curve',
                                           'rows': [{'name': '10Y&ndash;2Y spread',
                                                     'period': 'negative = inverted',
                                                     'series': 'T10Y2Y'}]},
                                          {'type': 'note',
                                           'text': 'Empty &mdash; no ingest has run yet. Source '
                                                   'and release date appear here.'},
                                          {'type': 'stories',
                                           'heading': 'related headlines',
                                           'items': [{}, {}]}]},
 'sections/relationships': {'title': 'relationships',
                            'h1': 'Relationships',
                            'section': 'relationships',
                            'tagline': 'how the tracked series move each other &mdash; derived, '
                                       'nothing ingested here',
                            'show_refreshed': False,
                            'crumb': [{'href': '/', 'label': 'cobalt'}, {'label': 'relationships'}],
                            'refresh': False,
                            'summarize': True,
                            'summary_body': 'No summary yet. Refresh the data elsewhere, then ask '
                                            'which chains are live today.',
                            'panels': [{'type': 'chains',
                                        'heading': 'prices &amp; policy',
                                        'chains': [{'nodes': [{'href': '/sections/macro/inflation',
                                                               'label': 'inflation'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/rates/treasuries',
                                                               'label': 'interest rates'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/indexes',
                                                               'label': 'equities'},
                                                              {'sep': '/'},
                                                              {'href': '/sections/rates/credit',
                                                               'label': 'credit'}],
                                                    'note': 'The central chain. Hot prints raise '
                                                            'the expected path of rates; higher '
                                                            'rates lower the value of distant '
                                                            'earnings and widen spreads. Watch the '
                                                            '2-year, which moves on expectations '
                                                            'before the Fed acts.'},
                                                   {'nodes': [{'href': '/sections/rates/treasuries',
                                                               'label': 'monetary policy'},
                                                              {'sep': '&rarr;'},
                                                              {'label': 'liquidity'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/indexes/us',
                                                               'label': 'financial markets'}],
                                                    'note': 'The slower version of the same '
                                                            'mechanism, acting through the '
                                                            'quantity of money rather than its '
                                                            'price. Liquidity has no single series '
                                                            '&mdash; read it off credit spreads '
                                                            'and the dollar.'},
                                                   {'nodes': [{'href': '/sections/rates/treasuries',
                                                               'label': 'interest rates'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/macro/growth',
                                                               'label': 'housing'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/companies/industrial',
                                                               'label': 'construction &amp; '
                                                                        'industrial'}],
                                                    'note': 'Housing is the most rate-sensitive '
                                                            'part of the economy and turns first. '
                                                            'Housing starts lead industrial demand '
                                                            'by quarters, so Caterpillar and Deere '
                                                            'confirm what starts already said.'}]},
                                       {'type': 'chains',
                                        'heading': 'demand &amp; growth',
                                        'chains': [{'nodes': [{'href': '/sections/macro/labor',
                                                               'label': 'labor market'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/companies/consumer',
                                                               'label': 'consumer spending'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/macro/growth',
                                                               'label': 'economic growth'}],
                                                    'note': 'Wages fund consumption, and '
                                                            'consumption is most of GDP. Jobless '
                                                            'claims turn well before the '
                                                            'unemployment rate does &mdash; watch '
                                                            'the weekly series, not the monthly '
                                                            'one.'},
                                                   {'nodes': [{'href': '/sections/macro/growth',
                                                               'label': 'economic growth'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/companies/industrial',
                                                               'label': 'industrial demand'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/commodities',
                                                               'label': 'commodities'}],
                                                    'note': 'Growth shows up as physical demand '
                                                            'before it shows up in GDP, which is '
                                                            'reported with a lag and revised. '
                                                            'Commodity prices are the real-time '
                                                            'version.'}]},
                                       {'type': 'chains',
                                        'heading': 'supply &amp; materials',
                                        'chains': [{'nodes': [{'href': '/sections/indexes/international',
                                                               'label': 'china &amp; global '
                                                                        'manufacturing'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/commodities',
                                                               'label': 'industrial metals'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/commodities',
                                                               'label': 'commodity prices'}],
                                                    'note': 'China is the marginal buyer of most '
                                                            'industrial metals, so copper reads as '
                                                            'a China indicator more than a US one. '
                                                            'Divergence between copper and US '
                                                            'growth usually means the story is in '
                                                            'Asia.'},
                                                   {'nodes': [{'href': '/sections/news/politics',
                                                               'label': 'geopolitical events'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/commodities',
                                                               'label': 'energy &amp; material '
                                                                        'supply'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/macro/inflation',
                                                               'label': 'inflation'}],
                                                    'note': 'The chain that runs backwards through '
                                                            'the first one: supply shocks raise '
                                                            'prices without any demand strength '
                                                            'behind them, which is why they are '
                                                            'the hardest case for monetary '
                                                            'policy.'},
                                                   {'nodes': [{'href': '/sections/ai-bubble',
                                                               'label': 'ai investment'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/companies/tech',
                                                               'label': 'semiconductors'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/commodities',
                                                               'label': 'electricity demand'},
                                                              {'sep': '&rarr;'},
                                                              {'href': '/sections/commodities',
                                                               'label': 'commodities'}],
                                                    'note': 'The newest chain and the least '
                                                            'settled. Capex guidance is the '
                                                            'upstream signal; uranium, natural gas '
                                                            'and copper are where it lands. If the '
                                                            'first link breaks, the rest unwinds '
                                                            'in order.'}]},
                                       {'type': 'note',
                                        'text': 'Grey nodes have no page of their own yet. Each '
                                                'chain is also a route &mdash; following the links '
                                                'walks the mechanism in order.'}]}}


SECTIONS = sorted({p['section'] for p in PAGES.values()})


def _check_invariants() -> None:
    """A row that prints a ticker must fetch that same ticker.

    This caught a real bug: the VOO row carried symbol ^GSPC, so the page
    showed the S&P 500 index level (7757) where the ETF price (~710) belonged —
    plausible-looking, wrong, and completely silent.
    """
    for slug, page in PAGES.items():
        for panel in page["panels"]:
            for row in panel.get("rows", []):
                ticker, symbol = row.get("ticker"), row.get("symbol")
                if ticker and symbol and ticker != symbol:
                    raise ValueError(
                        f"{slug}: row {row.get('name')!r} prints ticker {ticker} "
                        f"but fetches {symbol}"
                    )


_check_invariants()
